# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'elaine.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1167, 881)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Elainegui = QtWidgets.QLabel(self.centralwidget)
        self.Elainegui.setGeometry(QtCore.QRect(-10, 640, 1181, 241))
        self.Elainegui.setText("")
        self.Elainegui.setPixmap(QtGui.QPixmap("../6226435516042edfe1a4514a44e2023a.gif"))
        self.Elainegui.setScaledContents(True)
        self.Elainegui.setObjectName("Elainegui")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1050, 810, 93, 28))
        self.pushButton.setStyleSheet("font: 75 italic 10pt \"Comic Sans MS\";\n"
"color:rgb(16, 32, 255);\n"
"background:rgb(255, 137, 139);\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, 0, 1181, 211))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../walker4.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 210, 521, 451))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../CG.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(-10, 210, 331, 161))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../greeb.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(840, 210, 331, 171))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../greeb.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 370, 321, 271))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../st.gif"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(840, 380, 331, 261))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../ivan-bandura-EWVXMoIWlpA-unsplash.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
